name: Deploy to AWS Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.staging_lightsail_key }}

      - name: Disable SSH Host Key Checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Rsync Code to Lightsail (Exclude sensitive files)
        run: |
          rsync -avz --checksum --no-times --delete \
            --exclude=".git" \
            --exclude=".env" \
            --exclude="node_modules" \
            --exclude="writable" \
            --exclude="env" \
            --exclude=".htaccess" \
            --exclude="app/Config/App.php" \
            ./ root@213.136.84.162:/var/www/app
